// 货车信息模版
ybgapp.directive('car', function() {
    return {
        restrict: 'E',
        template: '<div class="single-box-image" >' 
        + '<div class="avatar-area">' 
        // + '<div class="img">' 
        // + '<img src="img/icon_car.gif">' 
        // + '</div>' 
        + '<span class="name">{{car_info.car_name}}</span>' 
        + ' </div>' 
        + ' <div class="list-block no-border">' 
        + ' <ul>' 
        + ' <li class="item-content">' 
        + ' <div class="item-inner">' 
        + '    <div class="item-title">' 
        + '        <span class="name">车牌号码：</span>' 
        + '        <span class="value">{{car_info.car_no}}</span>' 
        + '     </div>' 
        + '  </div>' 
        + ' </li>' 
        + '  <li class="item-content">' 
        + '   <div class="item-inner">' 
        + '   <div class="item-title">' 
        + '     <span class="name">车辆长宽高：</span>' 
        + '    <span class="value">长{{car_info.long}} / 宽{{car_info.width}} / 高{{car_info.high}}</span>' 
        + '   </div>' 
        + ' </div>' 
        + ' </li>' 
        + '<li class="item-content">' 
        + '   <div class="item-inner">' 
        + '   <div class="item-title">' 
        + '   <span class="name">最大承重：</span>' 
        + '   <span class="value">{{car_info.max_load}}</span>' 
        + ' </div>' 
        + ' </div>' 
        + '   </li>' 
        + '<li class="item-content">' 
        + '   <div class="item-inner">' 
        + '   <div class="item-title">' 
        + '   <span class="name">购买时间：</span>' 
        + '   <span class="value">{{car_info.buy_time}}</span>' 
        + ' </div>' 
        + ' </div>' 
        + '   </li>' 
        + '<li class="item-content">' 
        + '   <div class="item-inner">' 
        + '   <div class="item-title">' 
        + '   <span class="name">使用年限：</span>' 
        + '   <span class="value">{{car_info.work_year}}</span>' 
        + ' </div>' 
        + ' </div>' 
        + '   </li>' 
        + '<li class="item-content">' 
        + '   <div class="item-inner">' 
        + '  <div class="item-title">' 
        + ' <span class = "name" > 约行程里数： </span>' 
        + '   <span class="value">{{car_info.mileage}}</span >' 
        + ' </div>' 
        + ' </div >' 
        + ' </li>'
        + '<li class="item-content">' 
        + '   <div class="item-inner">' 
        + '  <div class="item-title">' 
        + ' <span class = "name" > 保险公司： </span>' 
        + '   <span class="value">{{car_info.insurer}}</span >' 
        + ' </div>' 
        + ' </div >' 
        + ' </li>' 
        + '<li class="item-content">' 
        + '   <div class="item-inner">' 
        + '  <div class="item-title">' 
        + ' <span class = "name" > 保险有效期： </span>' 
        + '   <span class="value">{{car_info.in_start}} ~ {{car_info.in_end}}</span >' 
        + ' </div>' 
        + ' </div >' 
        + ' </li>' 
        + '<li class="item-content">' 
        + '   <div class="item-inner">' 
        + '  <div class="item-title">' 
        + ' <span class = "name" > 发动机号： </span>' 
        + '   <span class="value">{{car_info.engine_no}}</span >' 
        + ' </div>' 
        + ' </div >' 
        + ' </li>' 
        + '<li class="item-content">' 
        + '   <div class="item-inner">' 
        + '  <div class="item-title">' 
        + ' <span class = "name" > 车架号： </span>' 
        + '   <span class="value">{{car_info.vin_no}}</span >' 
        + ' </div>' 
        + ' </div >' 
        + ' </li>'  
        + '   </ul >' 
        + ' </div>' 
        + '  <a href="#/me/car/edit?v={{car_info.car_id}}" class="yellow-ball-btn-large close-popup">' 
        + '   <span class=" icon icon-edit "></span>' 
        + '   <span class=" name ">编辑</span>' 
        + '  </a>' 
        + '</div>',
        replace: true
    };
});



